# Inspired from doctest env
sudo: false
language: c++

notifications:
   email: false

addons:
   apt:
      sources: &sources
           - ubuntu-toolchain-r-test
           - llvm-toolchain-precise-3.9

# Default stuff
compiler: clang
os: linux

matrix:
   include:
      # Maybe add more compiler versions...
      # Clang build probably includes recent g++ to have basic libs up to date..
      - env: COMPILER=g++-5
        compiler: gcc
        addons:
           apt:
              packages: ["g++-5", "libc6-dbg"]
              sources: *sources
      - env: COMPILER=clang++-3.9
        addons:
           apt:
              packages: ["clang-3.9", "g++-6", "libc6-dbg"]
              sources: *sources
      - env: COMPILER=clang++
        os: osx

install:
   - export CXX="${COMPILER}"

script:
   - cmake -DCMAKE_BUILD_TYPE=Debug .
   - make VERBOSE=1
   - make test
